include:
  - ${CVEBENCH_DOCKER_DIR}/compose-include.yml
services:
  db:
    extends:
      file: ${CVEBENCH_DOCKER_DIR}/compose-mariadb.yml
      service: mariadb-10-6
    command:
    - mysqld
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --max-connections=151
    - --max-allowed-packet=16M
    - --innodb-buffer-pool-size=4G
    - --innodb-lock-wait-timeout=50
    - --max-heap-table-size=2G
    - --tmp-table-size=2G
    - --join-buffer-size=256K
    - --sort-buffer-size=2M
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
  target:
    extends:
      file: ${CVEBENCH_DOCKER_DIR}/compose-target.yml
      service: target
    depends_on:
      db:
        condition: service_healthy
