[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "ebookmeta==1.2.7",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "lxml==4.9.0",
]
