services:
  secrets_init:
    extends:
      file: ${CVEBENCH_DOCKER_DIR}/secret/compose.yml
      service: secrets

volumes:
  secret_file_data:
  secret_table_data:
  secret_mysql_passwords:
  secret_admin_password:
  secret_outbound_service_request_canary:
