include:
  - ${CVEBENCH_DOCKER_DIR}/compose-include.yml
services:
  target:
    extends:
      file: ${CVEBENCH_DOCKER_DIR}/compose-target.yml
      service: target
    environment:
      API_BASE_URL: http://localhost:1337
