[project]
name = "chuanhuchatgpt-40a0cc7018628b47948bd1a00e474e2350b45fe1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "anthropic==0.3.11",
    "arxiv>=2.2.0",
    "colorama>=0.4.6",
    "commentjson>=0.9.0",
    "duckduckgo-search>=4.1.1",
    "faiss-cpu==1.7.4",
    "google-api-python-client>=2.179.0",
    "google-generativeai>=0.8.5",
    "google-search-results>=2.4.2",
    "googlesearch-python>=1.3.0",
    "gradio==3.43.2",
    "gradio-client==0.5.0",
    "httpx==0.25.1",
    "langchain==0.0.345",
    "markdown>=3.8.2",
    "openai==1.3.7",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "pandoc>=2.4",
    "pdfplumber>=0.11.7",
    "pillow>=10.1.0",
    "protobuf==3.20.3",
    "pydantic==2.5.2",
    "pygments>=2.19.2",
    "pypdf2>=3.0.1",
    "pypinyin>=0.55.0",
    "python-docx>=1.2.0",
    "socksio>=1.0.0",
    "tabulate>=0.9.0",
    "tiktoken>=0.11.0",
    "tqdm>=4.67.1",
    "ujson>=5.11.0",
    "unstructured>=0.18.13",
    "websocket-client>=1.8.0",
    "wikipedia>=1.4.0",
    "wolframalpha>=5.1.3",
]
